version: "3"

services:
  leaderboards:
    container_name: leaderboards
    image: ghcr.io/sharkadi-a/leaderboards:latest
    environment:
      - ConnectionStrings__Default=${PGSQL_CONNECTION_STRING}
      - Auth__0__UserName=${USER_NAME}
      - Auth__0__Password=${PASSWORD}
      - CryptoVectorString=${VECTOR}
    ports:
      - "6000:80"
    networks:
      - infra_shared
    restart: always

networks:
  infra_shared:
    external: true