version: "3"

services:
  leaderboards:
    container_name: leaderboards
    image: ghcr.io/sharkadi-a/andrey-games-leaderboards:latest
    environment:
      - ConnectionStrings__Default=User ID=user;Password=87aec3dbbc;Host=127.0.0.1;Port=5432;Database=leaderboards;Pooling=true;
      - Auth__0__UserName=user
      - Auth__1__UserName=87aec3dbbcls210957!
    ports:
      - "6000:80"
    restart: always