name: .NET 5 project build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --build-arg NAMESPACE="${{ github.repository_owner }}" --build-arg NUGET_KEY="${{ secrets.CR_PAT }}" --tag ${{ vars.PROJECT_NAME }}:latest --tag ghcr.io/${{ github.repository_owner }}/${{ vars.PROJECT_NAME }}:${{ github.run_number }}.${{ github.run_attempt }} --tag ghcr.io/${{ github.repository_owner }}/${{ vars.PROJECT_NAME }}:latest
        if: github.event_name != 'pull_request'

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --target tests --build-arg NAMESPACE="${{ github.repository_owner }}" --build-arg NUGET_KEY="${{ secrets.CR_PAT }}" --tag ${{ vars.PROJECT_NAME }}:latest --tag ghcr.io/${{ github.repository_owner }}/${{ vars.PROJECT_NAME }}:${{ github.run_number }}.${{ github.run_attempt }} --tag ghcr.io/${{ github.repository_owner }}/${{ vars.PROJECT_NAME }}:latest
        if: github.event_name == 'pull_request'