name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd src && docker build . --file Dockerfile --tag andrey-games-leaderboards:latest
      
    - name: Auth into Docker
      env:
        DOCKER_TOKEN: ${{ env.CR_PAT }}
      run: command echo $DOCKER_TOKEN | docker login ghcr.io -u sharkadi-a --password-stdin
    
    - name: Push into Docker Repository
      run: docker push ghcr.io/sharkadi-a/andrey-games-leaderboards:latest

