name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd src && docker build . --file Dockerfile --tag andrey-games-leaderboards --tag ghcr.io/sharkadi-a/andrey-games-leaderboards
      
    - name: Auth into Docker
      run: command echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u sharkadi-a --password-stdin
    
    - name: Push into Docker Repository
      run: docker push ghcr.io/sharkadi-a/andrey-games-leaderboards
      
    - name: Copy Docker Compose
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "docker-compose.yml"
        target: "/etc/infra/leaderboards/"
    
    - name: Run Docker Compose
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: | 
          command echo ${{ secrets.CR_PAT }}
          docker login ghcr.io -u sharkadi-a --password-stdin
          cd /etc/infra/leaderboards 
          docker-compose up -d

